name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 24.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint and coverage
        run: |
          npm i
          npm run check
        env:
          CI: true

      - name: Compile the book
        run: |
          npm run build
        env:
          CI: true

      - name: Commit files
        run: |
          git config --local user.email "tsidukciya[bot]@users.noreply.github.com"
          git config --local user.name "tsidukciya[bot]"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Compile the book"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
